# nmi | spring 2024
## homework 03 | gauss elimination, PA=LU factorization
## answers, final


### 00. useful stuff for n00bs


###### python, forward loops


In [ ]:
# https://docs.python.org/3/library/functions.html#func-range

# range(start with,stop before,step size)

print("\nin range(10) ~")
for i in range(10):
  print(i)

print("\nin range(1,10) ~")
for i in range(1,10):
  print(i)

print("\nin range(1,10,2) ~")
for i in range(1,10,2):
  print(i)

print("\nin range(0,10,2) ~")
for i in range(0,10,2):
  print(i)


###### python, backward loops

In [ ]:
print("\nin range(9,0,-1)) ~")
for i in range(9,0,-1):
  print(i)

print("\nin range(9,0-1,-1)) ~")
for i in range(9,-1,-1):
  print(i)

#https://docs.python.org/3/library/functions.html#reversed

print("\nin reversed(range(10)) ~")
for i in reversed(range(10)):
  print(i)

print("\nin reversed(range(1,10)) ~")
for i in reversed(range(1,10)):
  print(i)

print("\nin reversed(range(1,10+1)) ~")
for i in reversed(range(1,11)):
  print(i)


###### algorithm / pseudocode



```
# forward elimination

for j = 1 : n-1
  # check for zero on diagonal
  if abs(a(j,j))<eps; error("zero pivot encountered"); end

  # eliminate column j
  for i = j+1 : n

    # calc factor between rows
    mult = a(i,j)/a(j,j);

    # eliminate element i,j
    for k = j+1:n
      a(i,k) = a(i,k) - mult*a(j,k);
    end
    b(i) = b(i) - mult*b(j);
  end
end

# back substitution

for i = n : -1 : 1
  for j = i+1 : n
    b(i) = b(i) - a(i,j)*x(j);
  end
  x(i) = b(i)/a(i,i);
end
```


### q1. gauss elimination



#### a) (15 pts) code gauss elimination algorithm as a callable function in python.


###### algorithm



```
function gauss_elimination(A, b):
  n = len(A)

  # Forward elimination
  for k in range(n - 1):
    for i in range(k + 1, n):
      m = A[i][k] / A[k][k]
      for j in range(k + 1, n + 1):
        A[i][j] = A[i][j] - m * A[k][j]
      b[i] = b[i] - m * b[k]

  # Back substitution
  x = [0] * n
  for i in range(n - 1, -1, -1):
    sum = 0
    for j in range(i + 1, n):
      sum += A[i][j] * x[j]
    x[i] = (b[i] - sum) / A[i][i]

  return x
```


###### code


In [ ]:
def gauss_elimination(aa,ab,aeps):
  """
  solves system of linear equations Ax=b using gaussian elimination

  args:
    aa:   square matrix [A] of system coeffs
    ab:   vector [b] of RHS constants
    aeps: error bound

  returns:
    x: solution vector [x]

  raises:
    no error handling whatsoever bc i didnt feel like it
  """

  # initialize
  a = aa.copy()
  b = ab.copy()
  n = len(a)
  x = [0]*n

  # forward elimination
  for j in range(n-1): # 0 to 1
    # break if zero on diagonal
    if abs(a[j][j]) < aeps:
      break;

    # eliminate column j
    for i in range(j+1,n): # j+1 to 2

      # eliminate entry a(i,j) # i is row
      m = a[i][j]/a[j][j] # factor between rows
      for k in range(j+1,n):
        a[i][k] = a[i][k] - m*a[j][k]
      b[i] = b[i] - m*b[j]

  # backward substitution
  for i in reversed(range(n)):
    for j in range(i+1,n):
      b[i] = b[i] - a[i][j]*x[j]
    x[i] = b[i]/a[i][i]

  return x


#### b) (5 pts) call your function to solve the following system of equations,
</br></br>

\begin{align}
  x + 2y - z &= 3 \\
  2x + y - 2z &= 3\\
  -3x + y + z &= -6.
\end{align}
</br>


###### code


In [ ]:
#   x + 2y −  z =  3
#  2x +  y − 2z =  3
# −3x +  y +  z = −6
#
# answer [x,y,z] = [3,1,2]

A = [[1,2,-1],[2,1,-2],[-3,1,1]]
b = [3,3,-6]
eps = 1e-6

x = gauss_elimination(A,b,eps)
print(f"answer: {x}")


answer: [3.0, 1.0, 2.0]


#### c) <b><font color=blue>MATH 685 ONLY</font></b>. (5 pts) discuss the cost of solving this system of equations using gauss elimination.
</br>


###### code, python


In [ ]:
def gauss_elimination(A, b):
  """
  Solves a system of linear equations Ax = b using Gaussian elimination.

  Args:
      A: A square matrix representing the system coefficients.
      b: A vector representing the right-hand side constants.

  Returns:
      A list representing the solution vector x.

  Raises:
      ValueError: If the input matrix is not square or there are inconsistencies in the system.
  """

  n = len(A)
  if n != len(b) or n != len(A[0]):
    raise ValueError("Matrix and vector dimensions must match.")

  # Forward elimination
  for k in range(n - 1):
    for i in range(k + 1, n):
      # Check for division by zero (inconsistent system)
      if A[k][k] == 0:
        raise ValueError("Inconsistent system encountered.")
      # Calculate multiplier
      m = A[i][k] / A[k][k]
      # Eliminate elements below the pivot
      for j in range(k + 1, n + 1):
        A[i][j] = A[i][j] - m * A[k][j]
      b[i] = b[i] - m * b[k]

  # Back substitution
  x = [0] * n
  for i in range(n - 1, -1, -1):
    sum = 0
    for j in range(i + 1, n):
      sum += A[i][j] * x[j]
    # Check for division by zero (singular matrix)
    if A[i][i] == 0:
      raise ValueError("Singular matrix encountered.")
    x[i] = (b[i] - sum) / A[i][i]

  return x


### q2. <b><font color=green>MATH 385 ONLY</font></b>. (5 pts) LU factorization vs PA=LU factorization

what is naive gauss elimination? in relation, what are LU factorization and PA=LU factorization?
</br>


### q3. PA=LU factorization

a) <b><font color=green>MATH 385 ONLY</font></b>. (10 pts) solve the following system of equations using PA=LU factorization. show your work.
</br></br>

$$
\begin{bmatrix} 3 & 1 & 2 \\ 6 & 3 & 4 \\ 3 & 1 & 5 \end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}
= \begin{bmatrix} 0 \\ 1 \\ 3 \end{bmatrix}
$$
</br>

a) <b><font color=blue>MATH 685 ONLY</font></b>. (20 pts) code the PA=LU algorithm as function in python and use it to solve the same system of equations.
</br>


##### algorithm



```
# input a,b; output p,l,u, x

# forward elimination : PA = LU

p = identity
n = len(b)
u = a # start with, becomes lu

for j = 1 : n-1
  # permute
  for i = j+1 : n
    if abs(u[i,j])>abs(u[j,j]) then # swap # be careful!
      p(j),p(i) = p(i),p(j)
      u(j),u(i) = u(i),u(j)

  # check for zero on diagonal
  if abs(u(j,j))<eps; error("zero pivot encountered"); end

  # eliminate column j
  for i = j+1 : n

    # calc factor between rows
    mult = u(i,j)/u(j,j);
    u(i,j) = mult

    # eliminate element i,j
    for k = j+1:n
      u(i,k) = u(i,k) - mult*u(j,k);
    end
  end
end

# decompose lu ~ l,u
l = identity
for j = 1 : n-1
  for i = j+1 : n
    l(i,j) = u(i,j)
    u(i,j) = 0

# back substitution 1 : lc = pb

pb = p.b
c = [0]*n

# for lower triangular
for i = 1 : n
  for j = 1 : i
    pb(i) = pb(i) - l(i,j)*c(j);
  end
  c(i) = pb(i)/l(i,i);
end

# back substitution 2 : ux = c

x = [0]*n

# for upper triangular
for i = n : -1 : 1
  for j = i+1 : n
    c(i) = c(i) - u(i,j)*x(j);
  end
  x(i) = c(i)/u(i,i);
end
```


##### code


In [ ]:
#https://numpy.org/doc/stable/reference/generated/numpy.dot.html

import numpy as np

def f_palu(aa,ab):
  """
  aa : coefficient matrix
  ab : RHS

  solves Ax = b with PA=LU factorization

  returns
    : P permutation matrix
    : L lower triangular matrix
    : U upper triangular matrix
    : x solution vector
  """

  # forward elimination : PA = LU

  u = aa.copy() # start with, becomes lu
  n = len(u)
  p = np.identity(n)

  # permute
  for j in range(n-1):
    for i in range(j+1,n):
      if abs(u[i][j]) > abs(u[j][j]): # swap
        #p[j],p[i] = p[i],p[j] # doesnt work
        #u[j],u[i] = u[i],u[j] # doesnt work
        sigh = p[j].copy()
        p[j] = p[i].copy()
        p[i] = sigh.copy()
        sigh = u[j].copy()
        u[j] = u[i].copy()
        u[i] = sigh.copy()

    # barf for zero on diagonal
    if abs(u[j][j]) == 0:
      break;

    # eliminate column j
    for i in range(j+1,n):

      # calc factor between rows
      m = u[i][j]/u[j][j]
      u[i][j] = m # save some for later

      # eliminate element i,j
      for k in range(j+1,n):
        u[i][k] = u[i][k] - m*u[j][k]

  # decompose lu ~ l,u
  l = np.identity(n)
  for j in range(n-1):
    for i in range(j+1,n):
      l[i][j] = u[i][j]
      u[i][j] = 0

  # back substitution 1 : lc = pb

  pb = np.dot(p,ab.copy())
  c = [0]*n

  # for lower triangular
  for i in range(n):
    for j in range(i):
      pb[i] = pb[i] - l[i][j]*c[j]
    c[i] = pb[i]/l[i][i]

  # back substitution 2 : ux = c

  x = [0]*n

  # for upper triangular
  for i in reversed(range(n)):
    for j in range(i+1,n):
      c[i] = c[i] - u[i][j]*x[j] # note: c is altered
    x[i] = c[i]/u[i][i]

  return p,l,u,x

a = [[3,1,2],[6,3,4],[3,1,5]]
b = [[0],[1],[3]]

p,l,u,x = f_palu(a,b)
print("\np\n",p,"\nl\n",l,"\nu\n",u,"\nx\n",x)



p
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] 
l
 [[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 1.  1. ]] 
u
 [[6, 3, 4], [0, -0.5, 0.0], [0, 0, 3.0]] 
x
 [array([-1.]), array([1.]), array([1.])]
